---
title: "NO2 : dioxyde d'azote"
---

Le dioxyde d’azote (NO2) est émis lors des phénomènes de combustion, principalement par combinaison de l’azote et de l’oxygène de l’air. Les sources principales sont les véhicules et les installations de combustion.

Le NO2 se rencontre également à l’intérieur des locaux où fonctionnent des appareils au gaz tels que les gazinières, chauffe-eau, etc.

Une partie du dioxyde d'azote est également émise telle quelle dans l'atmosphère.

**Pollution générée :** le dioxyde d’azote participe aux phénomènes de pluies acides, à la formation de l’ozone troposphérique, dont il est un des précurseurs, à la dégradation de la couche d’ozone et à l’effet de serre. Enfin, même si les dépôts d’azote possèdent un certain pouvoir nutritif, à long terme, ces apports peuvent créer un déséquilibre nutritif dans le sol qui se répercute par la suite sur les végétaux.

 

**Effets sur la santé :** le dioxyde d'azote (NO2) est un gaz irritant pour les bronches. Il provoque des troubles respiratoires, des affections chroniques et des perturbations du transport de l'oxygène dans le sang, en se liant à l'hémoglobine.

Chez les asthmatiques, il augmente la fréquence et la gravité des crises. Chez l’enfant, il favorise les infections pulmonaires. Cependant, on estime aujourd’hui qu’il n’y a pas de risque cancérigène lié à l’exposition au dioxyde d’azote.

