---
title: "Polluants"
---
# H2S : hydrogène sulfuré

L’hydrogène sulfuré (H2S) est un gaz incolore, composant naturel du pétrole, à odeur caractéristique d’œufs pourris. Il se dégage des matières organiques en décomposition ou lors de l’utilisation du souffre et des sulfures dans l’industrie chimique. Étant plus lourd que l’air, il s’accumule dans les parties basses non ventilées…

Le dégagement se produit :

   * En présence de matières ou résidus organiques ou minéraux (production de sulfures)
   * Dans un espace confiné
    Sous l’effet d’une acidification (qui dépend du pH du milieu).

**NB :** la perception olfactive est décelable à très faible concentration mais ne constitue pas un seuil d’alerte suffisant car elle s’atténue jusqu’à disparaître au fur et à mesure qu’augmente la concentration de gaz (effet de sidération olfactive).

**Quels sont les risques ?**

L’hydrogène sulfuré est un gaz toxique qui pénètre par les voies respiratoires.
Compte tenu de son caractère insidieux, l’exposition à ce gaz revêt souvent un caractère accidentel qui peut être fatal.

Risques pour la santé :

   * Des intoxications aiguës (exposition de courte durée) : troubles respiratoires, irritations oculaires, conjonctivites, vertiges, céphalées, œdème aigu du poumon, pertes de connaissance (« plomb des vidangeurs »)
   * Des intoxications chroniques (exposition prolongée) : bronchites irritatives, irritations cutanées
   * Des pertes de connaissance à partir de 500 ppm
   * Une possibilité d’accident mortel très rapide en cas de fortes inhalations (> 1000 ppm) 

# NO : monoxyde d'azote

Il est principalement émis par toute combustion de combustibles fossiles.

**Pollution générée :** il contribue au phénomène des pluies acides et favorise la formation d’ozone.


**Effets sur la santé :** le monoxyde d'azote (NO) n'est pas toxique pour l'homme aux concentrations auxquelles on le rencontre dans l'environnement.

# NO2 : dioxyde d'azote

Le dioxyde d’azote (NO2) est émis lors des phénomènes de combustion, principalement par combinaison de l’azote et de l’oxygène de l’air. Les sources principales sont les véhicules et les installations de combustion.

Le NO2 se rencontre également à l’intérieur des locaux où fonctionnent des appareils au gaz tels que les gazinières, chauffe-eau, etc.

Une partie du dioxyde d'azote est également émise telle quelle dans l'atmosphère.

**Pollution générée :** le dioxyde d’azote participe aux phénomènes de pluies acides, à la formation de l’ozone troposphérique, dont il est un des précurseurs, à la dégradation de la couche d’ozone et à l’effet de serre. Enfin, même si les dépôts d’azote possèdent un certain pouvoir nutritif, à long terme, ces apports peuvent créer un déséquilibre nutritif dans le sol qui se répercute par la suite sur les végétaux.

 

**Effets sur la santé :** le dioxyde d'azote (NO2) est un gaz irritant pour les bronches. Il provoque des troubles respiratoires, des affections chroniques et des perturbations du transport de l'oxygène dans le sang, en se liant à l'hémoglobine.

Chez les asthmatiques, il augmente la fréquence et la gravité des crises. Chez l’enfant, il favorise les infections pulmonaires. Cependant, on estime aujourd’hui qu’il n’y a pas de risque cancérigène lié à l’exposition au dioxyde d’azote.

# NOx : oxydes d'azotes

Les oxydes d'azote (NOx) regroupent essentiellement deux molécules :

   *le monoxyde d'azote (NO) ;
   *le dioxyde d'azote (NO2).

Il existe trois mécanismes de formation des oxydes d'azote, et donc trois types de NOx :

   *les NOx thermiques, formés par combinaison chimique de l’oxygène et de l’azote de l’air lors d’une combustion à très haute température ;
   *les NOx combustibles, issus de l’oxydation de l’azote présent dans les combustibles ;
   *les NOx précoces, formés par combinaison chimique de l’azote de l’air avec des radicaux hydrocarbonés (CH et CH2, par exemple), qui se recombinent avec l’oxygène de l’air.

**Les sources d’émission des NOx**

Les oxydes d'azote proviennent essentiellement de procédés fonctionnant à haute température. Dans l’industrie, il s’agit des installations de combustion pour tout type de combustible (combustibles liquides fossiles, charbon, gaz naturel, biomasses, gaz de procédés...) et de procédés industriels (fabrication de verre, métaux, ciment...).

Les principales sources d'émission de NOx sont :

   *le transport routier ;
   *les secteurs de l'industrie et de la production d'énergie.

**Les impacts des NOx sur la santé**

Le NO2 est un gaz irritant, qui pénètre dans les ramifications les plus fines des voies respiratoires. Il peut provoquer des difficultés respiratoires ou une hyperréactivité bronchique chez les personnes sensibles et favoriser l'accroissement de la sensibilité des bronches aux infections chez l'enfant. Le NO2 est 40 fois plus toxique que le monoxyde de carbone (CO) et quatre fois plus toxique que le NO.

**Les impacts des NOx sur l’environnement**

Associés aux composés organiques volatils (COV), et sous l'effet du rayonnement solaire, les oxydes d'azote favorisent la formation d'ozone dans les basses couches de l'atmosphère (troposphère). En France, des dépassements des normes sanitaires dans l’air ambiant persistent, mais sont moins nombreux que par le passé. Les NOx contribuent aussi à la formation des retombées acides et à l'eutrophisation des écosystèmes. Les oxydes d'azote jouent enfin un rôle dans la formation de particules fines dans l’air ambiant.

# O3 : ozone

L’ozone est formé à partir de réactions chimiques entre les oxydes d’azote (NOx) et les composés organiques volatils (COV), sous l’effet du soleil. Comme il n’est pas émis directement dans l’air, on dit qu’il s’agit d’un polluant secondaire.

**Impact de l'ozone sur la sante**

L’ozone a un impact important sur la santé : il peut pénétrer profondément dans l’appareil respiratoire et provoquer une réaction inflammatoire bronchique au niveau cellulaire, d’où une toux sèche et une gêne respiratoire. Des effets cardiovasculaires sont également constatés. L’augmentation des niveaux d’ozone est corrélée à une augmentation des hospitalisations et à des décès prématurés.

# PM : particules fines

Les particules PM10, qui  regroupent les particules de diamètre inférieur à 10 µm, ont des sources multiples.

Les particules provoquent une altération de la santé respiratoire. 

La fraction fine, inférieure à 2.5 µm (PM2.5),  entraîne de plus une altération de la santé cardiovasculaire.


**Impact sur la santé**

Aux concentrations auxquelles sont exposées la plupart des populations urbaines et rurales des pays développés et en développement, les particules ont des effets nuisibles sur la santé. L'exposition chronique contribue à augmenter le risque de contracter des maladies cardiovasculaires et respiratoires, ainsi que des cancers pulmonaires. Les effets sur la santé sont dépendants de la taille des particules. Les particules grossières, fraction comprise entre 2.5 µm et 10 µm, ont  des effets sur la santé respiratoire. Concernant la fraction fine des particules, celles inférieures à 2.5 µm, elles impactent à long terme la santé cardiovasculaire.

**Impact sur l'environnement**

Les effets de salissure et de dégradation des monuments et bâtiment constituent les atteintes à l’environnement les plus visibles pour les particules.

**Source**

Les sources des particules sont multiples et influent sur la composition chimique et la taille de ces de ces dernières. 

La moitié des émissions de PM2.5 sont dues au secteur résidentiel et plus d'un quart au transport routier.

# SO2 : dioxyde de soufre

C’est un indicateur de la pollution liée aux combustibles fossiles.

**Impact sur la santé**
Le dioxyde de soufre affecte le système respiratoire, le fonctionnement des poumons et provoque des irritations oculaires. L’inflammation de l’appareil respiratoire entraine de la toux, une production de mucus, une exacerbation l’asthme, des bronchites chroniques et une sensibilisation aux infections respiratoires. 

**Impact sur l'environnement**
Concernant l’environnement, il contribue aux pluies acides, qui appauvrissent les milieux naturels (sols et végétaux) et dégradent les bâtiments.

**Source**
 Le dioxyde de soufre est émis lors de la combustion de matières fossiles, telles que le charbon, le pétrole et certains gaz contenant des impuretés en soufre, et lors de certains procédés industriels. Il est rejeté à plus de 50% par les activités industrielles, dont celles liées à la production d'énergie comme les centrales thermiques. Mais il est également émis par le chauffage résidentiel, commercial ou des entreprises. Les émissions de dioxyde de souffre dépendent de la teneur en soufre de ces combustibles.





