---
title: "SO2 : dioxyde de soufre"
---

C’est un indicateur de la pollution liée aux combustibles fossiles.

**Impact sur la santé**
Le dioxyde de soufre affecte le système respiratoire, le fonctionnement des poumons et provoque des irritations oculaires. L’inflammation de l’appareil respiratoire entraine de la toux, une production de mucus, une exacerbation l’asthme, des bronchites chroniques et une sensibilisation aux infections respiratoires. 

**Impact sur l'environnement**
Concernant l’environnement, il contribue aux pluies acides, qui appauvrissent les milieux naturels (sols et végétaux) et dégradent les bâtiments.

**Source**
 Le dioxyde de soufre est émis lors de la combustion de matières fossiles, telles que le charbon, le pétrole et certains gaz contenant des impuretés en soufre, et lors de certains procédés industriels. Il est rejeté à plus de 50% par les activités industrielles, dont celles liées à la production d'énergie comme les centrales thermiques. Mais il est également émis par le chauffage résidentiel, commercial ou des entreprises. Les émissions de dioxyde de souffre dépendent de la teneur en soufre de ces combustibles.
